#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_TEST,
    MUGSHOT_BROCK,
    MUGSHOT_MISTY,
    MUGSHOT_LT_SURGE,
    MUGSHOT_ERIKA,
    MUGSHOT_JANINE,
    MUGSHOT_SABRINA,
    MUGSHOT_BLAINE,
    MUGSHOT_GIOVANNI,
    MUGSHOT_LORELEI,
    MUGSHOT_BRUNO,
    MUGSHOT_AGATHA,
    MUGSHOT_LANCE,
    MUGSHOT_BLUE,
    MUGSHOT_FALKNER,
    MUGSHOT_BUGSY,
    MUGSHOT_WHITNEY,
    MUGSHOT_MORTY,
    MUGSHOT_CHUCK,
    MUGSHOT_JASMINE,
    MUGSHOT_PRYCE,
    MUGSHOT_CLAIR,
    MUGSHOT_WILL,
    MUGSHOT_KOGA,
    MUGSHOT_KAREN,
    MUGSHOT_CYNTHIA,
    MUGSHOT_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
