#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_TEST,
    MUGSHOT_MUDKIP,
    MUGSHOT_MUDKIP_SHINY,
    MUGSHOT_MIMIKYU,
    MUGSHOT_MIMIKYU_SHINY,
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    EMOTE_HAPPY = 0,
    EMOTE_NEUTRAL,
    EMOTE_SAD,
    EMOTE_UPSET,
    EMOTE_ANGRY,
    EMOTE_PENSIVE,
    EMOTE_LOVE,
    EMOTE_SURPRISE,
    EMOTE_CURIOUS,
    EMOTE_MUSIC,
    EMOTE_POISONED,
    EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
