#ifndef GUARD_CONSTANTS_PWT_TRAINERS_H
#define GUARD_CONSTANTS_PWT_TRAINERS_H

// Driftveil Tournament
#define PWT_TRAINER_DRIFTVEIL_HUGH          0
#define PWT_TRAINER_DRIFTVEIL_CHEREN        1
#define PWT_TRAINER_DRIFTVEIL_COLRESS       2
#define PWT_TRAINER_DRIFTVEIL_ROXIE         3
#define PWT_TRAINER_DRIFTVEIL_BURGH         4
#define PWT_TRAINER_DRIFTVEIL_ELESA         5
#define PWT_TRAINER_DRIFTVEIL_CLAY          6
#define PWT_TRAINER_DRIFTVEIL_X             7
#define PWT_TRAINER_DRIFTVEIL_MAKINA        8
#define PWT_TRAINER_DRIFTVEIL_FIDEL         9
#define PWT_TRAINER_DRIFTVEIL_THEODORA      10
#define PWT_TRAINER_DRIFTVEIL_ALLAN         11
#define PWT_TRAINER_DRIFTVEIL_JOCELYN       12
#define PWT_TRAINER_DRIFTVEIL_DMITRI        13
#define PWT_TRAINER_DRIFTVEIL_LEVINA        14
#define PWT_TRAINER_DRIFTVEIL_RYLAN         15
#define PWT_TRAINER_DRIFTVEIL_DESTINY       16
#define PWT_TRAINER_DRIFTVEIL_TED           17
#define PWT_TRAINER_DRIFTVEIL_SEAMUS        18
#define PWT_TRAINER_DRIFTVEIL_KENDAL        19
#define PWT_TRAINER_DRIFTVEIL_UNO           20
#define PWT_TRAINER_DRIFTVEIL_NANAKA        21
#define PWT_TRAINER_DRIFTVEIL_ENID          22
#define PWT_TRAINER_DRIFTVEIL_MASASHI       23
#define PWT_TRAINER_DRIFTVEIL_DORIAN        24
#define PWT_TRAINER_DRIFTVEIL_YARELI        25
#define PWT_TRAINER_DRIFTVEIL_MAKAYLA       26
#define PWT_TRAINER_DRIFTVEIL_TRISTAN       27
#define PWT_TRAINER_DRIFTVEIL_YOSEF         28
#define PWT_TRAINER_DRIFTVEIL_KARLIE        29
#define PWT_TRAINER_DRIFTVEIL_NAOMI         30
#define PWT_TRAINER_DRIFTVEIL_HERNANDO      31
#define PWT_TRAINER_DRIFTVEIL_INDY          32
#define PWT_TRAINER_DRIFTVEIL_HANNAH        33
#define PWT_TRAINER_DRIFTVEIL_CLARISSA      34
#define PWT_TRAINER_DRIFTVEIL_LESTER        35
#define PWT_TRAINER_DRIFTVEIL_MINORU        36
#define PWT_TRAINER_DRIFTVEIL_WILLA         37
#define PWT_TRAINER_DRIFTVEIL_HAILEY        38
#define PWT_TRAINER_DRIFTVEIL_KADEN         39
#define PWT_TRAINER_DRIFTVEIL_RODDY         40
#define PWT_TRAINER_DRIFTVEIL_CHLOE         41
#define PWT_TRAINER_DRIFTVEIL_TESSA         42
#define PWT_TRAINER_DRIFTVEIL_BERKE         43
#define PWT_TRAINER_DRIFTVEIL_SUNAN         44
#define PWT_TRAINER_DRIFTVEIL_SUDAPON       45
#define PWT_TRAINER_DRIFTVEIL_ANUPA         46
#define PWT_TRAINER_DRIFTVEIL_JAX           47
#define PWT_TRAINER_DRIFTVEIL_FRANCO        48
#define PWT_TRAINER_DRIFTVEIL_HAYDEN        49
#define PWT_TRAINER_DRIFTVEIL_MAXIE         50
#define PWT_TRAINER_DRIFTVEIL_BOBHIKO       51
#define PWT_TRAINER_DRIFTVEIL_BOBMASA       52
#define PWT_TRAINER_DRIFTVEIL_NOKKO         53
#define PWT_TRAINER_DRIFTVEIL_LIZ           54
#define PWT_TRAINER_DRIFTVEIL_YEN           55
#define PWT_TRAINER_DRIFTVEIL_CENTS         56
#define PWT_TRAINER_DRIFTVEIL_WANDA         57
#define PWT_TRAINER_DRIFTVEIL_EURO          58
#define PWT_TRAINER_DRIFTVEIL_CELSIUS       59
#define PWT_TRAINER_DRIFTVEIL_REN           60
#define PWT_TRAINER_DRIFTVEIL_KELLY         61
#define PWT_TRAINER_DRIFTVEIL_ALISON        62
#define PWT_TRAINER_DRIFTVEIL_BUTCH         63
#define PWT_TRAINER_DRIFTVEIL_CARVER        64
#define PWT_TRAINER_DRIFTVEIL_GAVIN         65
#define PWT_TRAINER_DRIFTVEIL_LARRY         66
// Everyone
// Kanto
#define PWT_TRAINER_KANTO_LEADER_BROCK         67
#define PWT_TRAINER_KANTO_LEADER_MISTY         68
#define PWT_TRAINER_KANTO_LEADER_LT_SURGE      69
#define PWT_TRAINER_KANTO_LEADER_ERIKA         70
#define PWT_TRAINER_KANTO_LEADER_JANINE        71
#define PWT_TRAINER_KANTO_LEADER_SABRINA       72
#define PWT_TRAINER_KANTO_LEADER_BLAINE        73
#define PWT_TRAINER_KANTO_LEADER_GIOVANNI      74
#define PWT_TRAINER_KANTO_ELITE_FOUR_LORELEI   75
#define PWT_TRAINER_KANTO_ELITE_FOUR_BRUNO     76
#define PWT_TRAINER_KANTO_ELITE_FOUR_AGATHA    77
#define PWT_TRAINER_KANTO_ELITE_FOUR_LANCE     78
#define PWT_TRAINER_KANTO_CHAMPION_BLUE        79
// Jhoto
#define PWT_TRAINER_JHOTO_LEADER_FALKNER       80
#define PWT_TRAINER_JHOTO_LEADER_BUGSY         81
#define PWT_TRAINER_JHOTO_LEADER_WHITNEY       82
#define PWT_TRAINER_JHOTO_LEADER_MORTY         83
#define PWT_TRAINER_JHOTO_LEADER_CHUCK         84
#define PWT_TRAINER_JHOTO_LEADER_JASMINE       85
#define PWT_TRAINER_JHOTO_LEADER_PRYCE         86
#define PWT_TRAINER_JHOTO_LEADER_CLAIR         87
#define PWT_TRAINER_JHOTO_ELITE_FOUR_WILL      88
#define PWT_TRAINER_JHOTO_ELITE_FOUR_KOGA      89
#define PWT_TRAINER_JHOTO_ELITE_FOUR_KAREN     90
// Hoenn
#define PWT_TRAINER_HOENN_LEADER_ROXANNE       91
#define PWT_TRAINER_HOENN_LEADER_BRAWLY        92
#define PWT_TRAINER_HOENN_LEADER_WATTSON       93
#define PWT_TRAINER_HOENN_LEADER_FLANNERY      94
#define PWT_TRAINER_HOENN_LEADER_NORMAN        95
#define PWT_TRAINER_HOENN_LEADER_WINONA        96
#define PWT_TRAINER_HOENN_LEADER_TATE          97
#define PWT_TRAINER_HOENN_LEADER_LIZA          98
#define PWT_TRAINER_HOENN_LEADER_JUAN          99
#define PWT_TRAINER_HOENN_ELITE_FOUR_SIDNEY    100
#define PWT_TRAINER_HOENN_ELITE_FOUR_PHOEBE    101
#define PWT_TRAINER_HOENN_ELITE_FOUR_GLACIA    102
#define PWT_TRAINER_HOENN_ELITE_FOUR_DRAKE     103
#define PWT_TRAINER_HOENN_CHAMPION_WALLACE     104
#define PWT_TRAINER_HOENN_CHAMPION_STEVEN      105
// Sinnoh
#define PWT_TRAINER_SINNOH_LEADER_ROARK        106
#define PWT_TRAINER_SINNOH_LEADER_GARDENIA     107
#define PWT_TRAINER_SINNOH_LEADER_MAYLENE      108
#define PWT_TRAINER_SINNOH_LEADER_CRASHER_WAKE 109
#define PWT_TRAINER_SINNOH_LEADER_FANTINA      110
#define PWT_TRAINER_SINNOH_LEADER_BYRON        111
#define PWT_TRAINER_SINNOH_LEADER_CANDICE      112
#define PWT_TRAINER_SINNOH_LEADER_VOLKNER      113
#define PWT_TRAINER_SINNOH_ELITE_FOUR_AARON    114
#define PWT_TRAINER_SINNOH_ELITE_FOUR_BERTHA   115
#define PWT_TRAINER_SINNOH_ELITE_FOUR_FLINT    116
#define PWT_TRAINER_SINNOH_ELITE_FOUR_LUCIAN   117
#define PWT_TRAINER_SINNOH_CHAMPION_CYNTHIA    118

// Tournament first and last value
#define PWT_TRAINER_DRIFTVEIL_START         PWT_TRAINER_DRIFTVEIL_HUGH
#define PWT_TRAINER_DRIFTVEIL_END           PWT_TRAINER_DRIFTVEIL_LARRY

#define PWT_TRAINER_KANTO_START             PWT_TRAINER_KANTO_LEADER_BROCK
#define PWT_TRAINER_KANTO_END               PWT_TRAINER_KANTO_CHAMPION_BLUE

#define PWT_TRAINER_JHOTO_START             PWT_TRAINER_JHOTO_LEADER_FALKNER
#define PWT_TRAINER_JHOTO_END               PWT_TRAINER_JHOTO_ELITE_FOUR_KAREN

#define PWT_TRAINER_HOENN_START             PWT_TRAINER_HOENN_LEADER_ROXANNE
#define PWT_TRAINER_HOENN_END               PWT_TRAINER_HOENN_CHAMPION_STEVEN

#define PWT_TRAINER_SINNOH_START            PWT_TRAINER_SINNOH_LEADER_ROARK
#define PWT_TRAINER_SINNOH_END              PWT_TRAINER_SINNOH_CHAMPION_CYNTHIA

#define PWT_TRAINER_INDIGO_LEAGUE_START     PWT_TRAINER_KANTO_START
#define PWT_TRAINER_INDIGO_LEAGUE_END       PWT_TRAINER_JHOTO_END

#define PWT_TRAINER_ROYALE_START            PWT_TRAINER_KANTO_START
#define PWT_TRAINER_ROYALE_END              PWT_TRAINER_SINNOH_END

// TODO - when certain trainers are beaten, flip flag to make them appear in the stands
#define PWT_TRAINERS_COUNT                     119

// NOTE: Player is TRAINER_PLAYER = 1023, so that is theoretical limit without more logic

#endif  // GUARD_CONSTANTS_PWT_TRAINERS_H
