#ifndef GUARD_CONSTANTS_QUESTS_H
#define GUARD_CONSTANTS_QUESTS_H

//questmenu scripting command params
#define QUEST_MENU_OPEN                 0   //opens the quest menu (questId = 0)
#define QUEST_MENU_UNLOCK_QUEST         1   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_SET_ACTIVE           2   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_SET_REWARD           3   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_COMPLETE_QUEST       4   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_CHECK_UNLOCKED       5   //checks if questId has been unlocked. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_INACTIVE       6 //check if a questID is inactive. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_ACTIVE         7   //checks if questId has been unlocked. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_REWARD         8  //checks if questId is in Reward state. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_COMPLETE       9   //checks if questId has been completed. Returns result to gSpecialVar_Result
#define QUEST_MENU_BUFFER_QUEST_NAME    10   //buffers a quest name to gStringVar1

// quest number defines
#define WINGS_OF_POWER                  0
#define MUTATED_WINGS                   1
#define BEASTS_OF_RESURRECTION          2
#define GOLEMS_OF_THE_ERAS              3
#define SPIRITS_OF_THE_SOUL             4
#define PRIMORDIAL_SEA                  5
#define DESOLATE_LAND                   6
#define ANCIENT_DRAGON_OF_CONQUEST      7
#define LEGENDS_LIE                     8
#define IMPRISONED_CURSES               9
#define SENTINELS_OF_THE_WILDS          10
#define GENIES_OF_NATURE                11
#define CHRONO_ALCHEMY                  12
#define TECHNO_REBIRTH                  13
#define CONCEALED_FORCES_OF_EXISTENCE   14
#define BROKEN_WORMHOLES                15
#define CELESTIAL_ECLIPSE               16
#define WARDENS_OF_THE_NEBULA           17
#define TWIN_SOULS                      18
#define ARTIFICIAL_POWER                19
#define TAO_KINGS                       20
#define DISTORTED_DIMENSIONS            21
#define GOLDEN_HEART_SILVER_SOUL        22
#define LONE_FIRE                       23
#define LUNAR_SPIRITS                   24
#define HEARTS_OF_THE_SEA               25
#define STALWART_SOLDIERS               26
#define MARTIAL_STUDENT                 27
#define KINGS_STEED                     28
#define STELLAR_SHRINE                  29
#define MYTHICAL_PIXIES                 30
#define FRAGMENTED_DNA                  31
#define CHALLENGE_THE_PROGENITOR        32
#define FALLEN_IDOL                     33
#define PRINCESS_JEWEL                  34
#define BURNING_WATER                   35
#define ARTIFICIAL_SOUL                 36
#define HIDDEN_SHADOW                   37
#define ZERAORA_QUEST                   38
#define MYSTERY_METAL                   39
#define ZARUDE_QUEST                    40
#define CORRUPTED_PECHA                 41

#define QUEST_COUNT     (CORRUPTED_PECHA + 1)


// sub-quest number defines
#define SUB_QUEST_WINGS_OF_POWER_1                  0
#define SUB_QUEST_WINGS_OF_POWER_2                  1
#define SUB_QUEST_WINGS_OF_POWER_3                  2
#define SUB_QUEST_WINGS_OF_POWER_4                  3
#define SUB_QUEST_WINGS_OF_POWER_5                  4
#define SUB_QUEST_WINGS_OF_POWER_6                  5
#define SUB_QUEST_WINGS_OF_POWER_7                  6
#define SUB_QUEST_WINGS_OF_POWER_8                  7
#define SUB_QUEST_WINGS_OF_POWER_9                  8
#define SUB_QUEST_MUTATED_WINGS_1                   9
#define SUB_QUEST_MUTATED_WINGS_2                   10
#define SUB_QUEST_MUTATED_WINGS_3                   11
#define SUB_QUEST_BEASTS_OF_RESURRECTION_1          12
#define SUB_QUEST_BEASTS_OF_RESURRECTION_2          13
#define SUB_QUEST_BEASTS_OF_RESURRECTION_3          14
#define SUB_QUEST_GOLEMS_OF_THE_ERAS_1              15
#define SUB_QUEST_GOLEMS_OF_THE_ERAS_2              16
#define SUB_QUEST_GOLEMS_OF_THE_ERAS_3              17
#define SUB_QUEST_GOLEMS_OF_THE_ERAS_4              18
#define SUB_QUEST_GOLEMS_OF_THE_ERAS_5              19
#define SUB_QUEST_GOLEMS_OF_THE_ERAS_6              20
#define SUB_QUEST_GOLEMS_OF_THE_ERAS_7              21
#define SUB_QUEST_GOLEMS_OF_THE_ERAS_8              22
#define SUB_QUEST_SPIRITS_OF_THE_SOUL_1             23
#define SUB_QUEST_SPIRITS_OF_THE_SOUL_2             24
#define SUB_QUEST_SPIRITS_OF_THE_SOUL_3             25
#define SUB_QUEST_SPIRITS_OF_THE_SOUL_4             26
#define SUB_QUEST_SPIRITS_OF_THE_SOUL_5             27
#define SUB_QUEST_SPIRITS_OF_THE_SOUL_6             28
#define SUB_QUEST_SPIRITS_OF_THE_SOUL_7             29
#define SUB_QUEST_PRIMORDIAL_SEA_1                  30
#define SUB_QUEST_PRIMORDIAL_SEA_2                  31
#define SUB_QUEST_DESOLATE_LAND_1                   32
#define SUB_QUEST_DESOLATE_LAND_2                   33
#define SUB_QUEST_ANCIENT_DRAGON_OF_CONQUEST_1      34
#define SUB_QUEST_ANCIENT_DRAGON_OF_CONQUEST_2      35
#define SUB_QUEST_LEGENDS_LIE_1                     36
#define SUB_QUEST_LEGENDS_LIE_2                     37
#define SUB_QUEST_LEGENDS_LIE_3                     38
#define SUB_QUEST_LEGENDS_LIE_4                     39
#define SUB_QUEST_LEGENDS_LIE_5                     40
#define SUB_QUEST_LEGENDS_LIE_6                     41
#define SUB_QUEST_LEGENDS_LIE_7                     42
#define SUB_QUEST_LEGENDS_LIE_8                     43
#define SUB_QUEST_IMPRISONED_CURSES_1               44
#define SUB_QUEST_IMPRISONED_CURSES_2               45
#define SUB_QUEST_IMPRISONED_CURSES_3               46
#define SUB_QUEST_IMPRISONED_CURSES_4               47
#define SUB_QUEST_IMPRISONED_CURSES_5               48
#define SUB_QUEST_IMPRISONED_CURSES_6               49
#define SUB_QUEST_IMPRISONED_CURSES_7               50
#define SUB_QUEST_IMPRISONED_CURSES_8               51
#define SUB_QUEST_IMPRISONED_CURSES_9               52
#define SUB_QUEST_SENTINELS_OF_THE_WILDS_1          53
#define SUB_QUEST_SENTINELS_OF_THE_WILDS_2          54
#define SUB_QUEST_SENTINELS_OF_THE_WILDS_3          55
#define SUB_QUEST_SENTINELS_OF_THE_WILDS_4          56
#define SUB_QUEST_SENTINELS_OF_THE_WILDS_5          57
#define SUB_QUEST_SENTINELS_OF_THE_WILDS_6          58
#define SUB_QUEST_GENIES_OF_NATURE_1                59
#define SUB_QUEST_GENIES_OF_NATURE_2                60
#define SUB_QUEST_GENIES_OF_NATURE_3                61
#define SUB_QUEST_GENIES_OF_NATURE_4                62
#define SUB_QUEST_GENIES_OF_NATURE_5                63
#define SUB_QUEST_GENIES_OF_NATURE_6                64
#define SUB_QUEST_GENIES_OF_NATURE_7                65
#define SUB_QUEST_GENIES_OF_NATURE_8                66
#define SUB_QUEST_CHRONO_ALCHEMY_1                  67
#define SUB_QUEST_CHRONO_ALCHEMY_2                  68
#define SUB_QUEST_CHRONO_ALCHEMY_3                  69
#define SUB_QUEST_TECHNO_REBIRTH_1                  70
#define SUB_QUEST_TECHNO_REBIRTH_2                  71
#define SUB_QUEST_TECHNO_REBIRTH_3                  72
#define SUB_QUEST_TECHNO_REBIRTH_4                  73
#define SUB_QUEST_TECHNO_REBIRTH_5                  74
#define SUB_QUEST_TECHNO_REBIRTH_6                  75
#define SUB_QUEST_TECHNO_REBIRTH_7                  76
#define SUB_QUEST_CONCEALED_FORCES_OF_EXISTENCE_1   77
#define SUB_QUEST_CONCEALED_FORCES_OF_EXISTENCE_2   78
#define SUB_QUEST_CONCEALED_FORCES_OF_EXISTENCE_3   79
#define SUB_QUEST_CONCEALED_FORCES_OF_EXISTENCE_4   80
#define SUB_QUEST_BROKEN_WORMHOLES_1                81
#define SUB_QUEST_BROKEN_WORMHOLES_2                82
#define SUB_QUEST_BROKEN_WORMHOLES_3                83
#define SUB_QUEST_BROKEN_WORMHOLES_4                84
#define SUB_QUEST_BROKEN_WORMHOLES_5                85
#define SUB_QUEST_CELESTIAL_ECLIPSE_1               86
#define SUB_QUEST_CELESTIAL_ECLIPSE_2               87
#define SUB_QUEST_CELESTIAL_ECLIPSE_3               88
#define SUB_QUEST_CELESTIAL_ECLIPSE_4               89
#define SUB_QUEST_WARDENS_OF_THE_NEBULA_1           90
#define SUB_QUEST_WARDENS_OF_THE_NEBULA_2           91
#define SUB_QUEST_WARDENS_OF_THE_NEBULA_3           92
#define SUB_QUEST_WARDENS_OF_THE_NEBULA_4           93
#define SUB_QUEST_WARDENS_OF_THE_NEBULA_5           94
#define SUB_QUEST_TWIN_SOULS_1                      95
#define SUB_QUEST_TWIN_SOULS_2                      96
#define SUB_QUEST_TWIN_SOULS_3                      97
#define SUB_QUEST_ARTIFICIAL_POWER_1                98
#define SUB_QUEST_ARTIFICIAL_POWER_2                99
#define SUB_QUEST_ARTIFICIAL_POWER_3                100
#define SUB_QUEST_ARTIFICIAL_POWER_4                101
#define SUB_QUEST_TAO_KINGS_1                       102
#define SUB_QUEST_TAO_KINGS_2                       103
#define SUB_QUEST_TAO_KINGS_3                       104
#define SUB_QUEST_TAO_KINGS_4                       105
#define SUB_QUEST_TAO_KINGS_5                       106
#define SUB_QUEST_TAO_KINGS_6                       107
#define SUB_QUEST_TAO_KINGS_7                       108
#define SUB_QUEST_DISTORTED_DIMENSIONS_1            109
#define SUB_QUEST_DISTORTED_DIMENSIONS_2            110
#define SUB_QUEST_DISTORTED_DIMENSIONS_3            111
#define SUB_QUEST_DISTORTED_DIMENSIONS_4            112
#define SUB_QUEST_DISTORTED_DIMENSIONS_5            113
#define SUB_QUEST_DISTORTED_DIMENSIONS_6            114
#define SUB_QUEST_DISTORTED_DIMENSIONS_7            115
#define SUB_QUEST_DISTORTED_DIMENSIONS_8            116
#define SUB_QUEST_GOLDEN_HEART_SILVER_SOUL_1        117
#define SUB_QUEST_GOLDEN_HEART_SILVER_SOUL_2        118
#define SUB_QUEST_GOLDEN_HEART_SILVER_SOUL_3        119
#define SUB_QUEST_GOLDEN_HEART_SILVER_SOUL_4        120
#define SUB_QUEST_GOLDEN_HEART_SILVER_SOUL_5        121
#define SUB_QUEST_GOLDEN_HEART_SILVER_SOUL_6        122
#define SUB_QUEST_LONE_FIRE_1                       123
#define SUB_QUEST_LONE_FIRE_2                       124
#define SUB_QUEST_LONE_FIRE_3                       125
#define SUB_QUEST_LUNAR_SPIRITS_1                   126
#define SUB_QUEST_LUNAR_SPIRITS_2                   127
#define SUB_QUEST_LUNAR_SPIRITS_3                   128
#define SUB_QUEST_LUNAR_SPIRITS_4                   129
#define SUB_QUEST_HEARTS_OF_THE_SEA_1               130
#define SUB_QUEST_HEARTS_OF_THE_SEA_2               131
#define SUB_QUEST_HEARTS_OF_THE_SEA_3               132
#define SUB_QUEST_HEARTS_OF_THE_SEA_4               133
#define SUB_QUEST_HEARTS_OF_THE_SEA_5               134
#define SUB_QUEST_HEARTS_OF_THE_SEA_6               135
#define SUB_QUEST_STALWART_SOLDIERS_1               136
#define SUB_QUEST_STALWART_SOLDIERS_2               137
#define SUB_QUEST_STALWART_SOLDIERS_3               138
#define SUB_QUEST_STALWART_SOLDIERS_4               139
#define SUB_QUEST_STALWART_SOLDIERS_5               140
#define SUB_QUEST_STALWART_SOLDIERS_6               141
#define SUB_QUEST_MARTIAL_STUDENT_1                 142
#define SUB_QUEST_MARTIAL_STUDENT_2                 143
#define SUB_QUEST_KINGS_STEED_1                     144
#define SUB_QUEST_KINGS_STEED_2                     145
#define SUB_QUEST_KINGS_STEED_3                     146
#define SUB_QUEST_KINGS_STEED_4                     147
#define SUB_QUEST_STELLAR_SHRINE_1                  148
#define SUB_QUEST_STELLAR_SHRINE_2                  149
#define SUB_QUEST_STELLAR_SHRINE_3                  150
#define SUB_QUEST_STELLAR_SHRINE_4                  151
#define SUB_QUEST_STELLAR_SHRINE_5                  152
#define SUB_QUEST_MYTHICAL_PIXIES_1                 153
#define SUB_QUEST_MYTHICAL_PIXIES_2                 154
#define SUB_QUEST_MYTHICAL_PIXIES_3                 155
#define SUB_QUEST_MYTHICAL_PIXIES_4                 156
#define SUB_QUEST_MYTHICAL_PIXIES_5                 157
#define SUB_QUEST_MYTHICAL_PIXIES_6                 158
#define SUB_QUEST_MYTHICAL_PIXIES_7                 159
#define SUB_QUEST_MYTHICAL_PIXIES_8                 160
#define SUB_QUEST_MYTHICAL_PIXIES_9                 161
#define SUB_QUEST_MYTHICAL_PIXIES_10                162
#define SUB_QUEST_MYTHICAL_PIXIES_11                163
#define SUB_QUEST_FRAGMENTED_DNA_1                  164
#define SUB_QUEST_FRAGMENTED_DNA_2                  165
#define SUB_QUEST_FRAGMENTED_DNA_3                  166
#define SUB_QUEST_FRAGMENTED_DNA_4                  167
#define SUB_QUEST_FRAGMENTED_DNA_5                  168
#define SUB_QUEST_FRAGMENTED_DNA_6                  169
#define SUB_QUEST_FRAGMENTED_DNA_7                  170
#define SUB_QUEST_FRAGMENTED_DNA_8                  171
#define SUB_QUEST_FRAGMENTED_DNA_9                  172
#define SUB_QUEST_FRAGMENTED_DNA_10                 173
#define SUB_QUEST_CHALLENGE_THE_PROGENITOR_1        174
#define SUB_QUEST_CHALLENGE_THE_PROGENITOR_2        175
#define SUB_QUEST_CHALLENGE_THE_PROGENITOR_3        176
#define SUB_QUEST_CHALLENGE_THE_PROGENITOR_4        177
#define SUB_QUEST_CHALLENGE_THE_PROGENITOR_5        178
#define SUB_QUEST_FALLEN_IDOL_1                     179
#define SUB_QUEST_FALLEN_IDOL_2                     180
#define SUB_QUEST_FALLEN_IDOL_3                     181
#define SUB_QUEST_FALLEN_IDOL_4                     182
#define SUB_QUEST_FALLEN_IDOL_5                     183
#define SUB_QUEST_FALLEN_IDOL_6                     184
#define SUB_QUEST_PRINCESS_JEWEL_1                  185
#define SUB_QUEST_PRINCESS_JEWEL_2                  186
#define SUB_QUEST_PRINCESS_JEWEL_3                  187
#define SUB_QUEST_PRINCESS_JEWEL_4                  188
#define SUB_QUEST_PRINCESS_JEWEL_5                  189
#define SUB_QUEST_PRINCESS_JEWEL_6                  190
#define SUB_QUEST_BURNING_WATER_1                   191
#define SUB_QUEST_BURNING_WATER_2                   192
#define SUB_QUEST_BURNING_WATER_3                   193
#define SUB_QUEST_ARTIFICIAL_SOUL_1                 194
#define SUB_QUEST_ARTIFICIAL_SOUL_2                 195
#define SUB_QUEST_ARTIFICIAL_SOUL_3                 196
#define SUB_QUEST_HIDDEN_SHADOW_1                   197
#define SUB_QUEST_HIDDEN_SHADOW_2                   198
#define SUB_QUEST_HIDDEN_SHADOW_3                   199
#define SUB_QUEST_ZERAORA_QUEST_1                   200
#define SUB_QUEST_ZERAORA_QUEST_2                   201
#define SUB_QUEST_ZERAORA_QUEST_3                   202
#define SUB_QUEST_MYSTERY_METAL_1                   203
#define SUB_QUEST_MYSTERY_METAL_2                   204
#define SUB_QUEST_MYSTERY_METAL_3                   205
#define SUB_QUEST_ZARUDE_QUEST_1                    206
#define SUB_QUEST_ZARUDE_QUEST_2                    207
#define SUB_QUEST_ZARUDE_QUEST_3                    208
#define SUB_QUEST_CORRUPTED_PECHA_1                 209
#define SUB_QUEST_CORRUPTED_PECHA_2                 210
#define SUB_QUEST_CORRUPTED_PECHA_3                 211


// sub-quest counts
#define QUEST_WINGS_OF_POWER_SUB_COUNT                  9
#define QUEST_MUTATED_WINGS_SUB_COUNT                   3
#define QUEST_BEASTS_OF_RESURRECTION_SUB_COUNT          3
#define QUEST_GOLEMS_OF_THE_ERAS_SUB_COUNT              8
#define QUEST_SPIRITS_OF_THE_SOUL_SUB_COUNT             7
#define QUEST_PRIMORDIAL_SEA_SUB_COUNT                  2
#define QUEST_DESOLATE_LAND_SUB_COUNT                   2
#define QUEST_ANCIENT_DRAGON_OF_CONQUEST_SUB_COUNT      2
#define QUEST_LEGENDS_LIE_SUB_COUNT                     8
#define QUEST_IMPRISONED_CURSES_SUB_COUNT               9
#define QUEST_SENTINELS_OF_THE_WILDS_SUB_COUNT          6
#define QUEST_GENIES_OF_NATURE_SUB_COUNT                8
#define QUEST_CHRONO_ALCHEMY_SUB_COUNT                  3
#define QUEST_TECHNO_REBIRTH_SUB_COUNT                  7
#define QUEST_CONCEALED_FORCES_OF_EXISTENCE_SUB_COUNT   4
#define QUEST_BROKEN_WORMHOLES_SUB_COUNT                5
#define QUEST_CELESTIAL_ECLIPSE_SUB_COUNT               4
#define QUEST_WARDENS_OF_THE_NEBULA_SUB_COUNT           5
#define QUEST_TWIN_SOULS_SUB_COUNT                      3
#define QUEST_ARTIFICIAL_POWER_SUB_COUNT                4
#define QUEST_TAO_KINGS_SUB_COUNT                       7
#define QUEST_DISTORTED_DIMENSIONS_SUB_COUNT            8
#define QUEST_GOLDEN_HEART_SILVER_SOUL_SUB_COUNT        6
#define QUEST_LONE_FIRE_SUB_COUNT                       3
#define QUEST_LUNAR_SPIRITS_SUB_COUNT                   4
#define QUEST_HEARTS_OF_THE_SEA_SUB_COUNT               6
#define QUEST_STALWART_SOLDIERS_SUB_COUNT               6
#define QUEST_MARTIAL_STUDENT_SUB_COUNT                 2
#define QUEST_KINGS_STEED_SUB_COUNT                     4
#define QUEST_STELLAR_SHRINE_SUB_COUNT                  5
#define QUEST_MYTHICAL_PIXIES_SUB_COUNT                 11
#define QUEST_FRAGMENTED_DNA_SUB_COUNT                  10
#define QUEST_CHALLENGE_THE_PROGENITOR_SUB_COUNT        5
#define QUEST_FALLEN_IDOL_SUB_COUNT                     6
#define QUEST_PRINCESS_JEWEL_SUB_COUNT                  6
#define QUEST_BURNING_WATER_SUB_COUNT                   3
#define QUEST_ARTIFICIAL_SOUL_SUB_COUNT                 3
#define QUEST_HIDDEN_SHADOW_SUB_COUNT                   3
#define QUEST_ZERAORA_QUEST_SUB_COUNT                   3
#define QUEST_MYSTERY_METAL_SUB_COUNT                   3
#define QUEST_ZARUDE_QUEST_SUB_COUNT                    3
#define QUEST_CORRUPTED_PECHA_SUB_COUNT                 3

#define SUB_QUEST_COUNT (QUEST_WINGS_OF_POWER_SUB_COUNT + QUEST_MUTATED_WINGS_SUB_COUNT + QUEST_BEASTS_OF_RESURRECTION_SUB_COUNT + QUEST_GOLEMS_OF_THE_ERAS_SUB_COUNT + QUEST_SPIRITS_OF_THE_SOUL_SUB_COUNT + QUEST_PRIMORDIAL_SEA_SUB_COUNT + QUEST_DESOLATE_LAND_SUB_COUNT + QUEST_ANCIENT_DRAGON_OF_CONQUEST_SUB_COUNT + QUEST_LEGENDS_LIE_SUB_COUNT + QUEST_IMPRISONED_CURSES_SUB_COUNT + QUEST_SENTINELS_OF_THE_WILDS_SUB_COUNT + QUEST_GENIES_OF_NATURE_SUB_COUNT + QUEST_CHRONO_ALCHEMY_SUB_COUNT + QUEST_TECHNO_REBIRTH_SUB_COUNT + QUEST_CONCEALED_FORCES_OF_EXISTENCE_SUB_COUNT + QUEST_BROKEN_WORMHOLES_SUB_COUNT + QUEST_CELESTIAL_ECLIPSE_SUB_COUNT + QUEST_WARDENS_OF_THE_NEBULA_SUB_COUNT + QUEST_TWIN_SOULS_SUB_COUNT + QUEST_ARTIFICIAL_POWER_SUB_COUNT + QUEST_TAO_KINGS_SUB_COUNT + QUEST_DISTORTED_DIMENSIONS_SUB_COUNT + QUEST_GOLDEN_HEART_SILVER_SOUL_SUB_COUNT + QUEST_LONE_FIRE_SUB_COUNT + QUEST_LUNAR_SPIRITS_SUB_COUNT + QUEST_HEARTS_OF_THE_SEA_SUB_COUNT + QUEST_STALWART_SOLDIERS_SUB_COUNT + QUEST_MARTIAL_STUDENT_SUB_COUNT + QUEST_KINGS_STEED_SUB_COUNT + QUEST_STELLAR_SHRINE_SUB_COUNT + QUEST_MYTHICAL_PIXIES_SUB_COUNT + QUEST_FRAGMENTED_DNA_SUB_COUNT + QUEST_CHALLENGE_THE_PROGENITOR_SUB_COUNT + QUEST_FALLEN_IDOL_SUB_COUNT + QUEST_PRINCESS_JEWEL_SUB_COUNT + QUEST_BURNING_WATER_SUB_COUNT + QUEST_ARTIFICIAL_SOUL_SUB_COUNT + QUEST_HIDDEN_SHADOW_SUB_COUNT + QUEST_ZERAORA_QUEST_SUB_COUNT + QUEST_MYSTERY_METAL_SUB_COUNT + QUEST_ZARUDE_QUEST_SUB_COUNT + QUEST_CORRUPTED_PECHA_SUB_COUNT)

#define QUEST_ARRAY_COUNT (SUB_QUEST_COUNT > QUEST_COUNT ? SUB_QUEST_COUNT : QUEST_COUNT)
#endif // GUARD_CONSTANTS_QUESTS_H