#ifndef GUARD_CONSTANTS_QUESTS_H
#define GUARD_CONSTANTS_QUESTS_H

//questmenu scripting command params
#define QUEST_MENU_OPEN                 0   //opens the quest menu (questId = 0)
#define QUEST_MENU_UNLOCK_QUEST         1   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_SET_ACTIVE           2   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_SET_REWARD           3   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_COMPLETE_QUEST       4   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_CHECK_UNLOCKED       5   //checks if questId has been unlocked. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_INACTIVE       6 //check if a questID is inactive. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_ACTIVE         7   //checks if questId has been unlocked. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_REWARD         8  //checks if questId is in Reward state. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_COMPLETE       9   //checks if questId has been completed. Returns result to gSpecialVar_Result
#define QUEST_MENU_BUFFER_QUEST_NAME    10   //buffers a quest name to gStringVar1

// quest number defines
#define QUEST_ARTICUNO              00
#define QUEST_ZAPDOS                01
#define QUEST_MOLTRES               02
#define QUEST_MEWTWO                03
#define QUEST_MEW                   04
#define QUEST_RAIKOU                05
#define QUEST_ENTEI                 06
#define QUEST_SUICUNE               07
#define QUEST_LUGIA                 08
#define QUEST_HO_OH                 09
#define QUEST_CELEBI                10
#define QUEST_REGIROCK              11
#define QUEST_REGICE                12
#define QUEST_REGISTEEL             13
#define QUEST_LATIAS                14
#define QUEST_LATIOS                15
#define QUEST_KYOGRE                16
#define QUEST_GROUDON               17
#define QUEST_RAYQUAZA              18
#define QUEST_JIRACHI               19
#define QUEST_DEOXYS                20
#define QUEST_UXIE                  21
#define QUEST_MESPRIT               22
#define QUEST_AZELF                 23
#define QUEST_DIALGA                24
#define QUEST_PALKIA                25
#define QUEST_HEATRAN               26
#define QUEST_REGIGIGAS             27
#define QUEST_GIRATINA              28
#define QUEST_CRESSELIA             29
#define QUEST_PHIONE                30
#define QUEST_MANAPHY               31
#define QUEST_DARKRAI               32
#define QUEST_SHAYMIN               33
#define QUEST_ARCEUS                34
#define QUEST_VICTINI               35
#define QUEST_COBALION              36
#define QUEST_TERRAKION             37
#define QUEST_VIRIZION              38
#define QUEST_TORNADUS              39
#define QUEST_THUNDURUS             40
#define QUEST_RESHIRAM              41
#define QUEST_ZEKROM                42
#define QUEST_LANDORUS              43
#define QUEST_KYUREM                44
#define QUEST_KELDEO                45
#define QUEST_MELOETTA              46
#define QUEST_GENESECT              47
#define QUEST_XERNEAS               48
#define QUEST_YVELTAL               49
#define QUEST_ZYGARDE               50
#define QUEST_DIANCIE               51
#define QUEST_HOOPA                 52
#define QUEST_VOLCANION             53
#define QUEST_TAPU_KOKO             54
#define QUEST_TAPU_LELE             55
#define QUEST_TAPU_BULU             56
#define QUEST_TAPU_FINI             57
#define QUEST_COSMOG                58
#define QUEST_SOLGALEO              59
#define QUEST_LUNALA                60
#define QUEST_NECROZMA              61
#define QUEST_MAGEARNA              62
#define QUEST_MARSHADOW             63
#define QUEST_ZERAORA               64
#define QUEST_MELTAN                65
#define QUEST_ZACIAN                66
#define QUEST_ZAMAZENTA             67
#define QUEST_ETERNATUS             68
#define QUEST_KUBFU                 69
#define QUEST_ZARUDE                70
#define QUEST_ARTICUNO_GALAR        71
#define QUEST_ZAPDOS_GALAR          72
#define QUEST_MOLTRES_GALAR         73
#define QUEST_REGIELEKI             74
#define QUEST_REGIDRAGO             75
#define QUEST_GLASTRIER             76
#define QUEST_SPECTRIER             77
#define QUEST_CALYREX               78
#define QUEST_ENAMORUS              79
#define QUEST_WO_CHIEN              80
#define QUEST_CHIEN_PAO             81
#define QUEST_TING_LU               82
#define QUEST_CHI_YU                83
#define QUEST_KORAIDON              84
#define QUEST_MIRAIDON              85
#define QUEST_OKIDOGI               86
#define QUEST_MUNKIDORI             87
#define QUEST_FEZANDIPITI           88
#define QUEST_OGERPON               89
#define QUEST_TERAPAGOS             90
#define QUEST_PECHARUNT             91

#define QUEST_COUNT     (QUEST_MELTAN + 1)//(QUEST_PECHARUNT + 1)

// sub-quest number defines
#define SUB_QUEST_ARTICUNO_1            000
#define SUB_QUEST_ARTICUNO_2            001
#define SUB_QUEST_ARTICUNO_3            002
#define SUB_QUEST_ZAPDOS_1              003
#define SUB_QUEST_ZAPDOS_2              004
#define SUB_QUEST_ZAPDOS_3              005
#define SUB_QUEST_MOLTRES_1             006
#define SUB_QUEST_MOLTRES_2             007
#define SUB_QUEST_MOLTRES_3             008
#define SUB_QUEST_MEWTWO_1              009
#define SUB_QUEST_MEWTWO_2              010
#define SUB_QUEST_MEWTWO_3              011
#define SUB_QUEST_MEW_1                 012
#define SUB_QUEST_MEW_2                 013
#define SUB_QUEST_MEW_3                 014
#define SUB_QUEST_RAIKOU_1              015
#define SUB_QUEST_RAIKOU_2              016
#define SUB_QUEST_RAIKOU_3              017
#define SUB_QUEST_ENTEI_1               018
#define SUB_QUEST_ENTEI_2               019
#define SUB_QUEST_ENTEI_3               020
#define SUB_QUEST_SUICUNE_1             021
#define SUB_QUEST_SUICUNE_2             022
#define SUB_QUEST_SUICUNE_3             023
#define SUB_QUEST_LUGIA_1               024
#define SUB_QUEST_LUGIA_2               025
#define SUB_QUEST_LUGIA_3               026
#define SUB_QUEST_HO_OH_1               027
#define SUB_QUEST_HO_OH_2               028
#define SUB_QUEST_HO_OH_3               029
#define SUB_QUEST_CELEBI_1              030
#define SUB_QUEST_CELEBI_2              031
#define SUB_QUEST_CELEBI_3              032
#define SUB_QUEST_REGIROCK_1            033
#define SUB_QUEST_REGIROCK_2            034
#define SUB_QUEST_REGIROCK_3            035
#define SUB_QUEST_REGICE_1              036
#define SUB_QUEST_REGICE_2              037
#define SUB_QUEST_REGICE_3              038
#define SUB_QUEST_REGISTEEL_1           039
#define SUB_QUEST_REGISTEEL_2           040
#define SUB_QUEST_REGISTEEL_3           041
#define SUB_QUEST_LATIAS_1              042
#define SUB_QUEST_LATIAS_2              043
#define SUB_QUEST_LATIAS_3              044
#define SUB_QUEST_LATIOS_1              045
#define SUB_QUEST_LATIOS_2              046
#define SUB_QUEST_LATIOS_3              047
#define SUB_QUEST_KYOGRE_1              048
#define SUB_QUEST_KYOGRE_2              049
#define SUB_QUEST_KYOGRE_3              050
#define SUB_QUEST_GROUDON_1             051
#define SUB_QUEST_GROUDON_2             052
#define SUB_QUEST_GROUDON_3             053
#define SUB_QUEST_RAYQUAZA_1            054
#define SUB_QUEST_RAYQUAZA_2            055
#define SUB_QUEST_RAYQUAZA_3            056
#define SUB_QUEST_JIRACHI_1             057
#define SUB_QUEST_JIRACHI_2             058
#define SUB_QUEST_JIRACHI_3             059
#define SUB_QUEST_DEOXYS_1              060
#define SUB_QUEST_DEOXYS_2              061
#define SUB_QUEST_DEOXYS_3              062
#define SUB_QUEST_UXIE_1                063
#define SUB_QUEST_UXIE_2                064
#define SUB_QUEST_UXIE_3                065
#define SUB_QUEST_MESPRIT_1             066
#define SUB_QUEST_MESPRIT_2             067
#define SUB_QUEST_MESPRIT_3             068
#define SUB_QUEST_AZELF_1               069
#define SUB_QUEST_AZELF_2               070
#define SUB_QUEST_AZELF_3               071
#define SUB_QUEST_DIALGA_1              072
#define SUB_QUEST_DIALGA_2              073
#define SUB_QUEST_DIALGA_3              074
#define SUB_QUEST_PALKIA_1              075
#define SUB_QUEST_PALKIA_2              076
#define SUB_QUEST_PALKIA_3              077
#define SUB_QUEST_HEATRAN_1             078
#define SUB_QUEST_HEATRAN_2             079
#define SUB_QUEST_HEATRAN_3             080
#define SUB_QUEST_REGIGIGAS_1           081
#define SUB_QUEST_REGIGIGAS_2           082
#define SUB_QUEST_REGIGIGAS_3           083
#define SUB_QUEST_GIRATINA_1            084
#define SUB_QUEST_GIRATINA_2            085
#define SUB_QUEST_GIRATINA_3            086
#define SUB_QUEST_CRESSELIA_1           087
#define SUB_QUEST_CRESSELIA_2           088
#define SUB_QUEST_CRESSELIA_3           089
#define SUB_QUEST_PHIONE_1              090
#define SUB_QUEST_PHIONE_2              091
#define SUB_QUEST_PHIONE_3              092
#define SUB_QUEST_MANAPHY_1             093
#define SUB_QUEST_MANAPHY_2             094
#define SUB_QUEST_MANAPHY_3             095
#define SUB_QUEST_DARKRAI_1             096
#define SUB_QUEST_DARKRAI_2             097
#define SUB_QUEST_DARKRAI_3             098
#define SUB_QUEST_SHAYMIN_1             099
#define SUB_QUEST_SHAYMIN_2             100
#define SUB_QUEST_SHAYMIN_3             101
#define SUB_QUEST_ARCEUS_1              102
#define SUB_QUEST_ARCEUS_2              103
#define SUB_QUEST_ARCEUS_3              104
#define SUB_QUEST_VICTINI_1             105
#define SUB_QUEST_VICTINI_2             106
#define SUB_QUEST_VICTINI_3             107
#define SUB_QUEST_COBALION_1            108
#define SUB_QUEST_COBALION_2            109
#define SUB_QUEST_COBALION_3            110
#define SUB_QUEST_TERRAKION_1           111
#define SUB_QUEST_TERRAKION_2           112
#define SUB_QUEST_TERRAKION_3           113
#define SUB_QUEST_VIRIZION_1            114
#define SUB_QUEST_VIRIZION_2            115
#define SUB_QUEST_VIRIZION_3            116
#define SUB_QUEST_TORNADUS_1            117
#define SUB_QUEST_TORNADUS_2            118
#define SUB_QUEST_TORNADUS_3            119
#define SUB_QUEST_THUNDURUS_1           120
#define SUB_QUEST_THUNDURUS_2           121
#define SUB_QUEST_THUNDURUS_3           122
#define SUB_QUEST_RESHIRAM_1            123
#define SUB_QUEST_RESHIRAM_2            124
#define SUB_QUEST_RESHIRAM_3            125
#define SUB_QUEST_ZEKROM_1              126
#define SUB_QUEST_ZEKROM_2              127
#define SUB_QUEST_ZEKROM_3              128
#define SUB_QUEST_LANDORUS_1            129
#define SUB_QUEST_LANDORUS_2            130
#define SUB_QUEST_LANDORUS_3            131
#define SUB_QUEST_KYUREM_1              132
#define SUB_QUEST_KYUREM_2              133
#define SUB_QUEST_KYUREM_3              134
#define SUB_QUEST_KELDEO_1              135
#define SUB_QUEST_KELDEO_2              136
#define SUB_QUEST_KELDEO_3              137
#define SUB_QUEST_MELOETTA_1            138
#define SUB_QUEST_MELOETTA_2            139
#define SUB_QUEST_MELOETTA_3            140
#define SUB_QUEST_GENESECT_1            141
#define SUB_QUEST_GENESECT_2            142
#define SUB_QUEST_GENESECT_3            143
#define SUB_QUEST_XERNEAS_1             144
#define SUB_QUEST_XERNEAS_2             145
#define SUB_QUEST_XERNEAS_3             146
#define SUB_QUEST_YVELTAL_1             147
#define SUB_QUEST_YVELTAL_2             148
#define SUB_QUEST_YVELTAL_3             149
#define SUB_QUEST_ZYGARDE_1             150
#define SUB_QUEST_ZYGARDE_2             151
#define SUB_QUEST_ZYGARDE_3             152
#define SUB_QUEST_DIANCIE_1             153
#define SUB_QUEST_DIANCIE_2             154
#define SUB_QUEST_DIANCIE_3             155
#define SUB_QUEST_HOOPA_1               156
#define SUB_QUEST_HOOPA_2               157
#define SUB_QUEST_HOOPA_3               158
#define SUB_QUEST_VOLCANION_1           159
#define SUB_QUEST_VOLCANION_2           160
#define SUB_QUEST_VOLCANION_3           161
#define SUB_QUEST_TAPU_KOKO_1           162
#define SUB_QUEST_TAPU_KOKO_2           163
#define SUB_QUEST_TAPU_KOKO_3           164
#define SUB_QUEST_TAPU_LELE_1           165
#define SUB_QUEST_TAPU_LELE_2           166
#define SUB_QUEST_TAPU_LELE_3           167
#define SUB_QUEST_TAPU_BULU_1           168
#define SUB_QUEST_TAPU_BULU_2           169
#define SUB_QUEST_TAPU_BULU_3           170
#define SUB_QUEST_TAPU_FINI_1           171
#define SUB_QUEST_TAPU_FINI_2           172
#define SUB_QUEST_TAPU_FINI_3           173
#define SUB_QUEST_COSMOG_1              174
#define SUB_QUEST_COSMOG_2              175
#define SUB_QUEST_COSMOG_3              176
#define SUB_QUEST_SOLGALEO_1            177
#define SUB_QUEST_SOLGALEO_2            178
#define SUB_QUEST_SOLGALEO_3            179
#define SUB_QUEST_LUNALA_1              180
#define SUB_QUEST_LUNALA_2              181
#define SUB_QUEST_LUNALA_3              182
#define SUB_QUEST_NECROZMA_1            183
#define SUB_QUEST_NECROZMA_2            184
#define SUB_QUEST_NECROZMA_3            185
#define SUB_QUEST_MAGEARNA_1            186
#define SUB_QUEST_MAGEARNA_2            187
#define SUB_QUEST_MAGEARNA_3            188
#define SUB_QUEST_MARSHADOW_1           189
#define SUB_QUEST_MARSHADOW_2           190
#define SUB_QUEST_MARSHADOW_3           191
#define SUB_QUEST_ZERAORA_1             192
#define SUB_QUEST_ZERAORA_2             193
#define SUB_QUEST_ZERAORA_3             194
#define SUB_QUEST_MELTAN_1              195
#define SUB_QUEST_MELTAN_2              196
#define SUB_QUEST_MELTAN_3              197
#define SUB_QUEST_ZACIAN_1              198
#define SUB_QUEST_ZACIAN_2              199
#define SUB_QUEST_ZACIAN_3              200
#define SUB_QUEST_ZAMAZENTA_1           201
#define SUB_QUEST_ZAMAZENTA_2           202
#define SUB_QUEST_ZAMAZENTA_3           203
#define SUB_QUEST_ETERNATUS_1           204
#define SUB_QUEST_ETERNATUS_2           205
#define SUB_QUEST_ETERNATUS_3           206
#define SUB_QUEST_KUBFU_1               207
#define SUB_QUEST_KUBFU_2               208
#define SUB_QUEST_KUBFU_3               209
#define SUB_QUEST_ZARUDE_1              210
#define SUB_QUEST_ZARUDE_2              211
#define SUB_QUEST_ZARUDE_3              212
#define SUB_QUEST_ARTICUNO_GALAR_1      213
#define SUB_QUEST_ARTICUNO_GALAR_2      214
#define SUB_QUEST_ARTICUNO_GALAR_3      215
#define SUB_QUEST_ZAPDOS_GALAR_1        216
#define SUB_QUEST_ZAPDOS_GALAR_2        217
#define SUB_QUEST_ZAPDOS_GALAR_3        218
#define SUB_QUEST_MOLTRES_GALAR_1       219
#define SUB_QUEST_MOLTRES_GALAR_2       220
#define SUB_QUEST_MOLTRES_GALAR_3       221
#define SUB_QUEST_REGIELEKI_1           222
#define SUB_QUEST_REGIELEKI_2           223
#define SUB_QUEST_REGIELEKI_3           224
#define SUB_QUEST_REGIDRAGO_1           225
#define SUB_QUEST_REGIDRAGO_2           226
#define SUB_QUEST_REGIDRAGO_3           227
#define SUB_QUEST_GLASTRIER_1           228
#define SUB_QUEST_GLASTRIER_2           229
#define SUB_QUEST_GLASTRIER_3           230
#define SUB_QUEST_SPECTRIER_1           231
#define SUB_QUEST_SPECTRIER_2           232
#define SUB_QUEST_SPECTRIER_3           233
#define SUB_QUEST_CALYREX_1             234
#define SUB_QUEST_CALYREX_2             235
#define SUB_QUEST_CALYREX_3             236
#define SUB_QUEST_ENAMORUS_1            237
#define SUB_QUEST_ENAMORUS_2            238
#define SUB_QUEST_ENAMORUS_3            239
#define SUB_QUEST_WO_CHIEN_1            240
#define SUB_QUEST_WO_CHIEN_2            241
#define SUB_QUEST_WO_CHIEN_3            242
#define SUB_QUEST_CHIEN_PAO_1           243
#define SUB_QUEST_CHIEN_PAO_2           244
#define SUB_QUEST_CHIEN_PAO_3           245
#define SUB_QUEST_TING_LU_1             246
#define SUB_QUEST_TING_LU_2             247
#define SUB_QUEST_TING_LU_3             248
#define SUB_QUEST_CHI_YU_1              249
#define SUB_QUEST_CHI_YU_2              250
#define SUB_QUEST_CHI_YU_3              251
#define SUB_QUEST_KORAIDON_1            252
#define SUB_QUEST_KORAIDON_2            253
#define SUB_QUEST_KORAIDON_3            254
#define SUB_QUEST_MIRAIDON_1            255
#define SUB_QUEST_MIRAIDON_2            256
#define SUB_QUEST_MIRAIDON_3            257
#define SUB_QUEST_OKIDOGI_1             258
#define SUB_QUEST_OKIDOGI_2             259
#define SUB_QUEST_OKIDOGI_3             260
#define SUB_QUEST_MUNKIDORI_1           261
#define SUB_QUEST_MUNKIDORI_2           262
#define SUB_QUEST_MUNKIDORI_3           263
#define SUB_QUEST_FEZANDIPITI_1         264
#define SUB_QUEST_FEZANDIPITI_2         265
#define SUB_QUEST_FEZANDIPITI_3         266
#define SUB_QUEST_OGERPON_1             267
#define SUB_QUEST_OGERPON_2             268
#define SUB_QUEST_OGERPON_3             269
#define SUB_QUEST_TERAPAGOS_1           270
#define SUB_QUEST_TERAPAGOS_2           271
#define SUB_QUEST_TERAPAGOS_3           272
#define SUB_QUEST_PECHARUNT_1           273
#define SUB_QUEST_PECHARUNT_2           274
#define SUB_QUEST_PECHARUNT_3           275

// sub-quest counts
#define QUEST_ARTICUNO_SUB_COUNT            3
#define QUEST_ZAPDOS_SUB_COUNT              3
#define QUEST_MOLTRES_SUB_COUNT             3
#define QUEST_MEWTWO_SUB_COUNT              3
#define QUEST_MEW_SUB_COUNT                 3
#define QUEST_RAIKOU_SUB_COUNT              3
#define QUEST_ENTEI_SUB_COUNT               3
#define QUEST_SUICUNE_SUB_COUNT             3
#define QUEST_LUGIA_SUB_COUNT               3
#define QUEST_HO_OH_SUB_COUNT               3
#define QUEST_CELEBI_SUB_COUNT              3
#define QUEST_REGIROCK_SUB_COUNT            3
#define QUEST_REGICE_SUB_COUNT              3
#define QUEST_REGISTEEL_SUB_COUNT           3
#define QUEST_LATIAS_SUB_COUNT              3
#define QUEST_LATIOS_SUB_COUNT              3
#define QUEST_KYOGRE_SUB_COUNT              3
#define QUEST_GROUDON_SUB_COUNT             3
#define QUEST_RAYQUAZA_SUB_COUNT            3
#define QUEST_JIRACHI_SUB_COUNT             3
#define QUEST_DEOXYS_SUB_COUNT              3
#define QUEST_UXIE_SUB_COUNT                3
#define QUEST_MESPRIT_SUB_COUNT             3
#define QUEST_AZELF_SUB_COUNT               3
#define QUEST_DIALGA_SUB_COUNT              3
#define QUEST_PALKIA_SUB_COUNT              3
#define QUEST_HEATRAN_SUB_COUNT             3
#define QUEST_REGIGIGAS_SUB_COUNT           3
#define QUEST_GIRATINA_SUB_COUNT            3
#define QUEST_CRESSELIA_SUB_COUNT           3
#define QUEST_PHIONE_SUB_COUNT              3
#define QUEST_MANAPHY_SUB_COUNT             3
#define QUEST_DARKRAI_SUB_COUNT             3
#define QUEST_SHAYMIN_SUB_COUNT             3
#define QUEST_ARCEUS_SUB_COUNT              3
#define QUEST_VICTINI_SUB_COUNT             3
#define QUEST_COBALION_SUB_COUNT            3
#define QUEST_TERRAKION_SUB_COUNT           3
#define QUEST_VIRIZION_SUB_COUNT            3
#define QUEST_TORNADUS_SUB_COUNT            3
#define QUEST_THUNDURUS_SUB_COUNT           3
#define QUEST_RESHIRAM_SUB_COUNT            3
#define QUEST_ZEKROM_SUB_COUNT              3
#define QUEST_LANDORUS_SUB_COUNT            3
#define QUEST_KYUREM_SUB_COUNT              3
#define QUEST_KELDEO_SUB_COUNT              3
#define QUEST_MELOETTA_SUB_COUNT            3
#define QUEST_GENESECT_SUB_COUNT            3
#define QUEST_XERNEAS_SUB_COUNT             3
#define QUEST_YVELTAL_SUB_COUNT             3
#define QUEST_ZYGARDE_SUB_COUNT             3
#define QUEST_DIANCIE_SUB_COUNT             3
#define QUEST_HOOPA_SUB_COUNT               3
#define QUEST_VOLCANION_SUB_COUNT           3
#define QUEST_TAPU_KOKO_SUB_COUNT           3
#define QUEST_TAPU_LELE_SUB_COUNT           3
#define QUEST_TAPU_BULU_SUB_COUNT           3
#define QUEST_TAPU_FINI_SUB_COUNT           3
#define QUEST_COSMOG_SUB_COUNT              3
#define QUEST_SOLGALEO_SUB_COUNT            3
#define QUEST_LUNALA_SUB_COUNT              3
#define QUEST_NECROZMA_SUB_COUNT            3
#define QUEST_MAGEARNA_SUB_COUNT            3
#define QUEST_MARSHADOW_SUB_COUNT           3
#define QUEST_ZERAORA_SUB_COUNT             3
#define QUEST_MELTAN_SUB_COUNT              3
#define QUEST_ZACIAN_SUB_COUNT              3
#define QUEST_ZAMAZENTA_SUB_COUNT           3
#define QUEST_ETERNATUS_SUB_COUNT           3
#define QUEST_KUBFU_SUB_COUNT               3
#define QUEST_ZARUDE_SUB_COUNT              3
#define QUEST_ARTICUNO_GALAR_SUB_COUNT      3
#define QUEST_ZAPDOS_GALAR_SUB_COUNT        3
#define QUEST_MOLTRES_GALAR_SUB_COUNT       3
#define QUEST_REGIELEKI_SUB_COUNT           3
#define QUEST_REGIDRAGO_SUB_COUNT           3
#define QUEST_GLASTRIER_SUB_COUNT           3
#define QUEST_SPECTRIER_SUB_COUNT           3
#define QUEST_CALYREX_SUB_COUNT             3
#define QUEST_ENAMORUS_SUB_COUNT            3
#define QUEST_WO_CHIEN_SUB_COUNT            3
#define QUEST_CHIEN_PAO_SUB_COUNT           3
#define QUEST_TING_LU_SUB_COUNT             3
#define QUEST_CHI_YU_SUB_COUNT              3
#define QUEST_KORAIDON_SUB_COUNT            3
#define QUEST_MIRAIDON_SUB_COUNT            3
#define QUEST_OKIDOGI_SUB_COUNT             3
#define QUEST_MUNKIDORI_SUB_COUNT           3
#define QUEST_FEZANDIPITI_SUB_COUNT         3
#define QUEST_OGERPON_SUB_COUNT             3
#define QUEST_TERAPAGOS_SUB_COUNT           3
#define QUEST_PECHARUNT_SUB_COUNT           3

// Intermediate counts to make line shorter
#define GEN1_SUB_QUEST_COUNT (QUEST_ARTICUNO_SUB_COUNT + QUEST_ZAPDOS_SUB_COUNT + QUEST_MOLTRES_SUB_COUNT + QUEST_MEWTWO_SUB_COUNT + QUEST_MEW_SUB_COUNT)
#define GEN2_SUB_QUEST_COUNT (QUEST_RAIKOU_SUB_COUNT + QUEST_ENTEI_SUB_COUNT + QUEST_SUICUNE_SUB_COUNT + QUEST_LUGIA_SUB_COUNT + QUEST_HO_OH_SUB_COUNT + QUEST_CELEBI_SUB_COUNT)
#define GEN3_SUB_QUEST_COUNT (QUEST_REGIROCK_SUB_COUNT + QUEST_REGICE_SUB_COUNT + QUEST_REGISTEEL_SUB_COUNT + QUEST_LATIAS_SUB_COUNT + QUEST_LATIOS_SUB_COUNT + QUEST_KYOGRE_SUB_COUNT + QUEST_GROUDON_SUB_COUNT + QUEST_RAYQUAZA_SUB_COUNT + QUEST_JIRACHI_SUB_COUNT + QUEST_DEOXYS_SUB_COUNT)
#define GEN4_SUB_QUEST_COUNT (QUEST_UXIE_SUB_COUNT + QUEST_MESPRIT_SUB_COUNT + QUEST_AZELF_SUB_COUNT + QUEST_DIALGA_SUB_COUNT + QUEST_PALKIA_SUB_COUNT + QUEST_HEATRAN_SUB_COUNT + QUEST_REGIGIGAS_SUB_COUNT + QUEST_GIRATINA_SUB_COUNT + QUEST_CRESSELIA_SUB_COUNT + QUEST_PHIONE_SUB_COUNT + QUEST_MANAPHY_SUB_COUNT + QUEST_DARKRAI_SUB_COUNT + QUEST_SHAYMIN_SUB_COUNT + QUEST_ARCEUS_SUB_COUNT)
#define GEN5_SUB_QUEST_COUNT (QUEST_VICTINI_SUB_COUNT + QUEST_COBALION_SUB_COUNT + QUEST_TERRAKION_SUB_COUNT + QUEST_VIRIZION_SUB_COUNT + QUEST_TORNADUS_SUB_COUNT + QUEST_THUNDURUS_SUB_COUNT + QUEST_RESHIRAM_SUB_COUNT + QUEST_ZEKROM_SUB_COUNT + QUEST_LANDORUS_SUB_COUNT + QUEST_KYUREM_SUB_COUNT + QUEST_KELDEO_SUB_COUNT + QUEST_MELOETTA_SUB_COUNT + QUEST_GENESECT_SUB_COUNT)
#define GEN6_SUB_QUEST_COUNT (QUEST_XERNEAS_SUB_COUNT + QUEST_YVELTAL_SUB_COUNT + QUEST_ZYGARDE_SUB_COUNT + QUEST_DIANCIE_SUB_COUNT + QUEST_HOOPA_SUB_COUNT + QUEST_VOLCANION_SUB_COUNT)
#define GEN7_SUB_QUEST_COUNT (QUEST_TAPU_KOKO_SUB_COUNT + QUEST_TAPU_LELE_SUB_COUNT + QUEST_TAPU_BULU_SUB_COUNT + QUEST_TAPU_FINI_SUB_COUNT + QUEST_COSMOG_SUB_COUNT + QUEST_SOLGALEO_SUB_COUNT + QUEST_LUNALA_SUB_COUNT + QUEST_NECROZMA_SUB_COUNT + QUEST_MAGEARNA_SUB_COUNT + QUEST_MARSHADOW_SUB_COUNT + QUEST_ZERAORA_SUB_COUNT + QUEST_MELTAN_SUB_COUNT)
#define GEN8_SUB_QUEST_COUNT (QUEST_ZACIAN_SUB_COUNT + QUEST_ZAMAZENTA_SUB_COUNT + QUEST_ETERNATUS_SUB_COUNT + QUEST_KUBFU_SUB_COUNT + QUEST_ZARUDE_SUB_COUNT + QUEST_ARTICUNO_GALAR_SUB_COUNT + QUEST_ZAPDOS_GALAR_SUB_COUNT + QUEST_MOLTRES_GALAR_SUB_COUNT + QUEST_REGIELEKI_SUB_COUNT + QUEST_REGIDRAGO_SUB_COUNT + QUEST_GLASTRIER_SUB_COUNT + QUEST_SPECTRIER_SUB_COUNT + QUEST_CALYREX_SUB_COUNT + QUEST_ENAMORUS_SUB_COUNT)
#define GEN9_SUB_QUEST_COUNT (QUEST_WO_CHIEN_SUB_COUNT + QUEST_CHIEN_PAO_SUB_COUNT + QUEST_TING_LU_SUB_COUNT + QUEST_CHI_YU_SUB_COUNT + QUEST_KORAIDON_SUB_COUNT + QUEST_MIRAIDON_SUB_COUNT + QUEST_OKIDOGI_SUB_COUNT + QUEST_MUNKIDORI_SUB_COUNT + QUEST_FEZANDIPITI_SUB_COUNT + QUEST_OGERPON_SUB_COUNT + QUEST_TERAPAGOS_SUB_COUNT + QUEST_PECHARUNT_SUB_COUNT)
#define SUB_QUEST_COUNT      (GEN1_SUB_QUEST_COUNT + GEN2_SUB_QUEST_COUNT + GEN3_SUB_QUEST_COUNT + GEN4_SUB_QUEST_COUNT + GEN5_SUB_QUEST_COUNT + GEN6_SUB_QUEST_COUNT + GEN7_SUB_QUEST_COUNT) //(GEN1_SUB_QUEST_COUNT + GEN2_SUB_QUEST_COUNT + GEN3_SUB_QUEST_COUNT + GEN4_SUB_QUEST_COUNT + GEN5_SUB_QUEST_COUNT + GEN6_SUB_QUEST_COUNT + GEN7_SUB_QUEST_COUNT + GEN8_SUB_QUEST_COUNT + GEN9_SUB_QUEST_COUNT)

#define QUEST_ARRAY_COUNT (SUB_QUEST_COUNT > QUEST_COUNT ? SUB_QUEST_COUNT : QUEST_COUNT)
#endif // GUARD_CONSTANTS_QUESTS_H