PWT_Text_Potential1::
	.string "The best candidate to be a champ!$"

PWT_Text_Potential2::
	.string "A sure-finalist team.$"

PWT_Text_Potential3::
	.string "A likely top-three finisher.$"

PWT_Text_Potential4::
	.string "A candidate to finish first.$"

PWT_Text_Potential5::
	.string "A team with top-class potential.$"

PWT_Text_Potential6::
	.string "The dark horse team this tournament.$"

PWT_Text_Potential7::
	.string "A better-than-average team.$"

PWT_Text_Potential8::
	.string "This tournament's average team.$"

PWT_Text_Potential9::
	.string "A team with average potential.$"

PWT_Text_Potential10::
	.string "A weaker-than-average team.$"

PWT_Text_Potential11::
	.string "A team looking for its first win.$"

PWT_Text_Potential12::
	.string "One win will make this team proud.$"

PWT_Text_Potential13::
	.string "Overall, a weak team.$"

PWT_Text_Potential14::
	.string "A team with very low potential.$"

PWT_Text_Potential15::
	.string "A team unlikely to win the tournament.$"

PWT_Text_Potential16::
	.string "The team most unlikely to win.$"

PWT_Text_StyleRiskDisaster::
	.string "Willing to risk total disaster at times.$"

PWT_Text_StyleEndureLongBattles::
	.string "Skilled at enduring long battles.$"

PWT_Text_StyleVariesTactics::
	.string "Varies tactics to suit the opponent.$"

PWT_Text_StyleToughWinningPattern::
	.string "Has a tough winning pattern.$"

PWT_Text_StyleUsesVeryRareMove::
	.string "Occasionally uses a very rare move.$"

PWT_Text_StyleUsesStartlingMoves::
	.string "Uses startling and disruptive moves.$"

PWT_Text_StyleConstantlyWatchesHP::
	.string "Constantly watches HP in battle.$"

PWT_Text_StyleStoresAndLoosesPower::
	.string "Good at storing then loosing power.$"

PWT_Text_StyleEnfeeblesFoes::
	.string "Skilled at enfeebling foes.$"

PWT_Text_StylePrefersLuckTactics::
	.string "Prefers tactics that rely on luck.$"

PWT_Text_StyleRegalAtmosphere::
	.string "Attacks with a regal atmosphere.$"

PWT_Text_StylePowerfulLowPPMoves::
	.string "Attacks with powerful, low-PP moves.$"

PWT_Text_StyleEnfeebleThenAttack::
	.string "Skilled at enfeebling, then attacking.$"

PWT_Text_StyleBattlesWhileEnduring::
	.string "Battles while enduring all attacks.$"

PWT_Text_StyleUpsetsFoesEmotionally::
	.string "Skilled at upsetting foes emotionally.$"

PWT_Text_StyleStrongAndStraightforward::
	.string "Uses strong and straightforward moves.$"

PWT_Text_StyleAggressivelyStrongMoves::
	.string "Aggressively uses strong moves.$"

PWT_Text_StyleCleverlyDodgesAttacks::
	.string "Battles while cleverly dodging attacks.$"

PWT_Text_StyleUsesUpsettingMoves::
	.string "Skilled at using upsetting attacks.$"

PWT_Text_StyleUsesPopularMoves::
	.string "Uses many popular moves.$"

PWT_Text_StyleHasPowerfulComboMoves::
	.string "Has moves for powerful combinations.$"

PWT_Text_StyleUsesHighProbabilityMoves::
	.string "Uses high-probability attacks.$"

PWT_Text_StyleAggressivelySpectacularMoves::
	.string "Aggressively uses spectacular moves.$"

PWT_Text_StyleEmphasizesOffenseOverDefense::
	.string "Emphasizes offense over defense.$"

PWT_Text_StyleEmphasizesDefenseOverOffense::
	.string "Emphasizes defense over offense.$"

PWT_Text_StyleAttacksQuicklyStrongMoves::
	.string "Attacks quickly with strong moves.$"

PWT_Text_StyleUsesAddedEffectMoves::
	.string "Often uses moves with added effects.$"

PWT_Text_StyleUsesBalancedMixOfMoves::
	.string "Uses a well-balanced mix of moves.$"

PWT_Text_StyleSampleMessage1::
	.string "This is sample message 1.$"

PWT_Text_StyleSampleMessage2::
	.string "This is sample message 2.$"

PWT_Text_StyleSampleMessage3::
	.string "This is sample message 3.$"

PWT_Text_StyleSampleMessage4::
	.string "This is sample message 4.$"

PWT_Text_EmphasizesHPAndAtk::
	.string "Emphasizes HP and ATTACK.$"

PWT_Text_EmphasizesHPAndDef::
	.string "Emphasizes HP and DEFENSE.$"

PWT_Text_EmphasizesHPAndSpeed::
	.string "Emphasizes HP and SPEED.$"

PWT_Text_EmphasizesHPAndSpAtk::
	.string "Emphasizes HP and SP. ATTACK.$"

PWT_Text_EmphasizesHPAndSpDef::
	.string "Emphasizes HP and SP. DEFENSE.$"

PWT_Text_EmphasizesAtkAndDef::
	.string "Emphasizes ATTACK and DEFENSE.$"

PWT_Text_EmphasizesAtkAndSpeed::
	.string "Emphasizes ATTACK and SPEED.$"

PWT_Text_EmphasizesAtkAndSpAtk::
	.string "Emphasizes ATTACK and SP. ATTACK.$"

PWT_Text_EmphasizesAtkAndSpDef::
	.string "Emphasizes ATTACK and SP. DEFENSE.$"

PWT_Text_EmphasizesDefAndSpeed::
	.string "Emphasizes DEFENSE and SPEED.$"

PWT_Text_EmphasizesDefAndSpAtk::
	.string "Emphasizes DEFENSE and SP. ATTACK.$"

PWT_Text_EmphasizesDefAndSpDef::
	.string "Emphasizes DEFENSE and SP. DEFENSE.$"

PWT_Text_EmphasizesSpeedAndSpAtk::
	.string "Emphasizes SPEED and SP. ATTACK.$"

PWT_Text_EmphasizesSpeedAndSpDef::
	.string "Emphasizes SPEED and SP. DEFENSE.$"

PWT_Text_EmphasizesSpAtkAndSpDef::
	.string "Emphasizes SP. ATTACK and SP. DEFENSE.$"

PWT_Text_EmphasizesHP::
	.string "Emphasizes HP.$"

PWT_Text_EmphasizesAtk::
	.string "Emphasizes ATTACK.$"

PWT_Text_EmphasizesDef::
	.string "Emphasizes DEFENSE.$"

PWT_Text_EmphasizesSpeed::
	.string "Emphasizes SPEED.$"

PWT_Text_EmphasizesSpAtk::
	.string "Emphasizes SP. ATTACK.$"

PWT_Text_EmphasizesSpDef::
	.string "Emphasizes SP. DEFENSE.$"

PWT_Text_NeglectsHPAndAtk::
	.string "Neglects HP and ATTACK.$"

PWT_Text_NeglectsHPAndDef::
	.string "Neglects HP and DEFENSE.$"

PWT_Text_NeglectsHPAndSpeed::
	.string "Neglects HP and SPEED.$"

PWT_Text_NeglectsHPAndSpAtk::
	.string "Neglects HP and SP. ATTACK.$"

PWT_Text_NeglectsHPAndSpDef::
	.string "Neglects HP and SP. DEFENSE.$"

PWT_Text_NeglectsAtkAndDef::
	.string "Neglects ATTACK and DEFENSE.$"

PWT_Text_NeglectsAtkAndSpeed::
	.string "Neglects ATTACK and SPEED.$"

PWT_Text_NeglectsAtkAndSpAtk::
	.string "Neglects ATTACK and SP. ATTACK.$"

PWT_Text_NeglectsAtkAndSpDef::
	.string "Neglects ATTACK and SP. DEFENSE.$"

PWT_Text_NeglectsDefAndSpeed::
	.string "Neglects DEFENSE and SPEED.$"

PWT_Text_NeglectsDefAndSpAtk::
	.string "Neglects DEFENSE and SP. ATTACK.$"

PWT_Text_NeglectsDefAndSpDef::
	.string "Neglects DEFENSE and SP. DEFENSE.$"

PWT_Text_NeglectsSpeedAndSpAtk::
	.string "Neglects SPEED and SP. ATTACK.$"

PWT_Text_NeglectsSpeedAndSpDef::
	.string "Neglects SPEED and SP. DEFENSE.$"

PWT_Text_NeglectsSpAtkAndSpDef::
	.string "Neglects SP. ATTACK and SP. DEFENSE.$"

PWT_Text_NeglectsHP::
	.string "Neglects HP.$"

PWT_Text_NeglectsAtk::
	.string "Neglects ATTACK.$"

PWT_Text_NeglectsDef::
	.string "Neglects DEFENSE.$"

PWT_Text_NeglectsSpeed::
	.string "Neglects SPEED.$"

PWT_Text_NeglectsSpAtk::
	.string "Neglects SP. ATTACK.$"

PWT_Text_NeglectsSpDef::
	.string "Neglects SP. DEFENSE.$"

PWT_Text_RaisesMonsWellBalanced::
	.string "Raises POKéMON in a well-balanced way.$"

PWT_Text_LetTheBattleBegin::
	.string "Let the battle begin!$"

PWT_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} won using {STR_VAR_2}!$"

PWT_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} became the champ!$"

PWT_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} won by default!$"

PWT_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} won outright by default!$"

PWT_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} won without using a move!$"

PWT_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} won outright with no moves!$"

PWT_Text_Round1Match1::
	.string "Round 1, Match 1$"

PWT_Text_Round1Match2::
	.string "Round 1, Match 2$"

PWT_Text_Round1Match3::
	.string "Round 1, Match 3$"

PWT_Text_Round1Match4::
	.string "Round 1, Match 4$"

PWT_Text_Round1Match5::
	.string "Round 1, Match 5$"

PWT_Text_Round1Match6::
	.string "Round 1, Match 6$"

PWT_Text_Round1Match7::
	.string "Round 1, Match 7$"

PWT_Text_Round1Match8::
	.string "Round 1, Match 8$"

PWT_Text_Round2Match1::
	.string "Round 2, Match 1$"

PWT_Text_Round2Match2::
	.string "Round 2, Match 2$"

PWT_Text_Round2Match3::
	.string "Round 2, Match 3$"

PWT_Text_Round2Match4::
	.string "Round 2, Match 4$"

PWT_Text_SemifinalMatch1::
	.string "Semifinal Match 1$"

PWT_Text_SemifinalMatch2::
	.string "Semifinal Match 2$"

PWT_Text_FinalMatch::
	.string "Final Match$"
